// ── Domain types ─────────────────────────────────────────────────────────────

export type Role = 'viewer' | 'contributor' | 'moderator' | 'admin';

export type RoleRequestStatus = 'pending' | 'accepted' | 'rejected';

export type FriendRequestStatus = 'pending' | 'accepted' | 'rejected';

// ── DB row shapes ─────────────────────────────────────────────────────────────

export interface User {
  id: number;
  username: string;
  email: string;
}

export interface UserWithHash extends User {
  password_hash: string;
  created_at: Date;
}

/** Row from the `following` table */
export interface Member {
  userid: number;
  spaceid: number;
  role: Role;
}

export interface Space {
  id: number;
  spacename: string;
  created_at: Date;
}

export interface RoleRequest {
  id: number;
  user_id: number;
  space_id: number;
  role: Role;
  status: RoleRequestStatus;
  created_at: Date;
  expires_at: Date | null;
}

export interface InviteLink {
  id: number;
  token: string;
  space_id: number;
  role: Role;
  expires_at: Date | null;
  single_use: boolean;
  used: boolean;
  created_at: Date;
}

export interface FriendRequest {
  id: number;
  from_user_id: number;
  to_user_id: number;
  status: FriendRequestStatus;
  created_at: Date;
  responded_at: Date | null;
}

export interface Friend {
  id: number;
  username: string;
  updated_at: Date;
}

export interface UserSearchResult {
  id: number;
  username: string;
  relationship: 'friends' | 'pending' | 'none';
}

export interface SpaceFolder {
  id: number;
  space_id: number;
  created_by: number;
  name: string;
  parent_id: number | null;   // null = top-level folder in the space
  updated_at: Date;
  deleted: boolean;
  trashed_at: Date | null;
}

export interface SpaceItem {
  photo_id: string;           // UUID, generated by DB
  space_id: number;
  uploader_id: number;
  folder_id: number | null;   // null = item lives at space root
  file_path: string;          // relative to UPLOADS_ROOT, e.g. spaces/42/originals/uuid.jpg
  thumbnail_path: string;
  content_hash: string | null;
  perceptual_hash: string | null;
  mime_type: string;
  size_bytes: number;
  display_name: string;       // original filename shown to users
  captured_at: Date | null;   // from EXIF, null if unavailable
  uploaded_at: Date;
  trashed_at: Date | null;    // null = active; set when moved to recycle bin
  updated_at: Date;
  deleted: boolean;
}

// ── JWT payload ───────────────────────────────────────────────────────────────

export interface JwtPayload {
  id: number;
  username: string;
}

// ── Express request augmentation ─────────────────────────────────────────────
// Adds typed properties set by our middleware to Express.Request.

declare global {
  namespace Express {
    interface Request {
      /** Set by `authenticate` middleware after JWT verification. */
      user: JwtPayload;
      /** Set by `isMember` middleware — the caller's membership row. */
      member: Member;
      /** Set by `deltaSync` middleware — the high-water timestamp to query from. */
      since: Date;
    }
  }
}
